apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: education-provider-registry-public-api-temp.test.teacherservices.cloud
spec:
  ingressClassName: nginx
  rules:
  - host: education-provider-registry-public-api-temp.test.teacherservices.cloud
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: education-provider-registry-public-api-development
            port:
              number: 80
